# This file will be configured by the user after they create a new site from this template.
backend:
  name: github
  # IMPORTANT: THESE ARE PLACEHOLDERS FOR YOUR CLIENT TO FILL IN
  repo: studionannipierifrancesco/studionannipierifrancesco.github.io
  branch: main
  # This will point to the client's authentication service
  base_url: https://red-shadow-5326.studionannipierifrancesco.workers.dev

site_url: https://www.studiofisiolistiklivornopisa.it

media_folder: "public/images"
public_folder: "/test-svelte-blog/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
